#headless service
apiVersion: v1
kind: Service
metadata:
  name: mysql #서비스의 이름
  labels:
    app: mysql 
spec: 
  ports:
    - port: 3306 #연결될 pod의 container의 port
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-pod
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql #사용할 서비스 이름
  replicas: 1   #총 pod 1개만 생성 
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10 # 종료 요청 후 10초간 기다리도록 한다. db 손상 방지 위해서  
      containers:
        - name: mysql 
          image: mysql:5.6     
          ports:
            - containerPort: 3306 #컨테이너에서 개방할 포트 번호
              name: mysql #port이름
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql #컨테이너의 이 경로에 이름이 data인 볼륨 mount
  volumeClaimTemplates: #걍 pvc만드는거임 #얘는 pvc만 만들수있음 # pvc를 여기에서 지정해서 pod마다 pvc와 pv를 생성하도록 하는 부분 이거쓰면 pod의 replica개수에 맞게 pvc랑 pv동적으로 할당됨
  - metadata:
      name: data #pvc의 이름 
    spec:
      storageClassName: standard #이 storage에 pv요청함
      accessModes:
        - ReadWriteOnce #하나의 노드에서만 현재 볼륨이 읽기/쓰기로 마운트 될 수 있다
      resources:
        requests:
          storage: 1Gi
      











      #storage를 aws를 이용할지
      #storage aws안하면 replica를 적개 해서 pvc랑 pv정적으로 다 만들고 거기에 hostpath해서 node경로 적어야함
      #만약에 statefulset해서 replica를 3개 이렇게 많이 하면 pod가 여러개 만들어지니까 pv, pvc여러개 만들기 번거롭 그니까 statefulset에서 vct이용해서 pv동적으로 만든다 그러기위해서는 pv를 가져올 storage필요함
      #정해야될게 statefulset pod수 몇개로 할지 1,2개 하면 hostpath하면되고
      #3개이상 하면 storage써야함 ㅇㅇ storage쓰기  
