#mysql-headless service
#fastapi컨테이너가 접근하기 위해서 mysql컨테이너 노출함
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306 #이 service의 port
      #targetPort: 3306 #mysql 컨테이너 port