apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app: db
    app.kubernetes.io/name: db
data:
  primary.cnf: |
    [mysqld]
    log-bin
  replica.cnf: |
    [mysqld]
    super-read-only