#읽기 모드
apiVersion: v1
kind: Service
metadata:
  name: db-read
  labels:
    app: db
    app.kubernetes.io/name: db
spec: #읽기 작업은 헤드리스일 필요가 없다
  ports:
  - name: mysql
    port: 3306
  selector:
    app: db
    app.kubernetes.io/name: mysql
